version: "3"
    
services:
  #mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DB: foodb
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_volume:/var/lib/mysql
  
  #wordpress
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB: foodb
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASS: 1234
    volumes:
      - wordpress_volume:/var/www/html
volumes:
  mysql_volume: {}
  wordpress_volume: {}
